version: "3.9"

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  wp:
    driver: local
    name: wp
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/Documents/wordpress
  db:
    driver: local
    name: db
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/Documents/DB
  logs:
    driver: local
    name: logs
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/Documents/logs
  adm:
    driver: local
    name: adm
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/Documents/adminer

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    build: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception
    expose:
      - "3306"
    restart: always

  nginx:
    container_name: nginx
    image: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - wp:/var/www/mehill.42.fr/html
      - adm:/var/www/adminer.42.fr/html
    networks:
      - inception
    depends_on:
      - wordpress
      - adminer
    restart: always

  wordpress:
    container_name: wordpress
    image: wordpress
    build: ./requirements/wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
      - redis
    expose:
      - "9000"
    volumes:
      - wp:/var/www/mehill.42.fr/html
    networks:
      - inception
    restart: always
  
  redis:
    container_name: redis
    image: redis
    build: ./requirements/bonus/redis
    env_file:
      - .env
    expose:
      - "6379"
    networks:
      - inception
    volumes:
      - logs:/var/log/redis/
    restart: always

  ftp-server:
    container_name: ftp-server
    image: ftp-server
    build: ./requirements/bonus/ftp-server
    env_file:
      - .env
    ports:
      - 20:20
      - 21:21
      - 21100-21110:21100-21110
    volumes:
      - "wp:/home/vsftpd/mehill"
      - "logs:/var/log/vsftpd"
    networks:
      - inception
    restart: always
  
  adminer:
    container_name: adminer
    image: adminer
    build: ./requirements/bonus/adminer
    env_file:
      - .env
    expose:
      - "9000"
    volumes:
      - adm:/var/www/adminer.42.fr/html
    networks:
      - inception
    restart: always
